# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# provincial statistics.py
# Created on: 2024-10-25 08:42:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.CheckOutExtension('Spatial')
import os

arcpy.env.overwriteOutput = True

Province_shp = "C:\\Users\\Zengx\\Desktop\\ArcGIS\\Lab\\Lab6\\Data 6.1 Precipitation"
output_table_dir = r"C:\Users\Zengx\Desktop\ArcGIS\Lab\Lab6\Data 6.1 Precipitation\output_tables"

tifdir = r"C:\Users\Zengx\Desktop\ArcGIS\Lab\Lab6\Data 6.1 Precipitation\month"
for tif in os.listdir(tifdir):
    if tif.endswith('.tif'):
        input_file = tifdir + os.sep + tif
        print(input_file)
        output_file = tifdir + os.sep + tif[:-4] + '_Zone.tif'
        print(output_file)
        arcpy.gp.ZonalStatisticsAsTable_sa(Province_shp, "NAME", input_file, output_table_dir, "DATA", "ALL")
        print(tif + ' is done!')
print('All files are finished!')
    



# Process: Zonal Statistics as Table


